# Generated by Django 5.2.17 on 2026-09-27 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='título')),
                ('key', models.SlugField(unique=True, verbose_name='chave')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='publicada')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('period', models.CharField(blank=True, max_length=100, verbose_name='período')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='publicada')),
            ],
            options={
                'verbose_name': 'referência',
                'verbose_name_plural': 'referências',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ReferenceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='texto')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='portfolio.reference', verbose_name='referência')),
            ],
            options={
                'verbose_name': 'link',
                'verbose_name_plural': 'links',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='título')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='URL ou caminho da imagem')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('detail', models.TextField(blank=True, verbose_name='detalhes')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='publicada')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='portfolio.category', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'obra',
                'verbose_name_plural': 'obras',
                'ordering': ('position', 'id'),
            },
        ),
    ]
