# Generated by Django 5.2.17 on 2026-09-27 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_seed_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='image',
            field=models.ImageField(blank=True, upload_to='obras/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='imagem enviada'),
        ),
        migrations.AlterField(
            model_name='work',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='URL alternativa da imagem'),
        ),
    ]
