# Generated by Django 5.2.17 on 2026-09-27 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_work_image_alter_work_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('photo', models.ImageField(blank=True, upload_to='sobre/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='foto enviada')),
                ('photo_url', models.CharField(blank=True, max_length=500, verbose_name='URL alternativa da foto')),
                ('bio', models.TextField(verbose_name='biografia (separe os parágrafos com linha em branco)')),
            ],
            options={
                'verbose_name': 'perfil do portfólio',
                'verbose_name_plural': 'perfil do portfólio',
            },
        ),
    ]
