# Generated by Django 5.2.17 on 2026-09-27 22:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_seed_artist_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fundos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='imagem enviada')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='publicado')),
            ],
            options={
                'verbose_name': 'imagem de fundo',
                'verbose_name_plural': 'imagens de fundo',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail de contato'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='contact_form_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='endpoint do formulário'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, verbose_name='frase de apresentação'),
        ),
    ]
